name: Application CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer Install
        run: composer install
      - name: PHPUnit
        run: composer tests

